dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz

before_install:
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/ && ./configure --prefix=/usr LDFLAGS="-lm" && make && sudo make install && cd .. && rm -r ta-lib


install:
    - python3 -m pip install -e .[dev]
    - python3 -m pip install -U --target=`pwd` --no-deps pyEX  # install latest pyEX base
    - git checkout pyEX/studies  # the above install clobbers source, so restore

script:
  - make lint
  - make tests

after_success:
    - codecov --token 2ae3f29d-c055-4e83-a1a9-b32526489d64

branches:
  only:
  - main 

notifications:
  email: false
