dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

before_install:
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/ && ./configure --prefix=/usr LDFLAGS="-lm" && make && sudo make install && cd .. && rm -r ta-lib

install: 
  - python3 -m pip install -r requirements.txt && python3 -m pip install -e .[dev]

script: make test

install:
    - pip install -r requirements.txt
    - pip install -U pytest pytest-cov flake8 pylint codecov

script: make test

after_success:
    - codecov --token 2ae3f29d-c055-4e83-a1a9-b32526489d64

branches:
  only:
  - master

notifications:
  email: false
