language: python
cache: pip

python:
  - "3.6"

before_install:
  - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
  - tar -xvzf ta-lib-0.4.0-src.tar.gz
  - cd ta-lib/ && ./configure --prefix=/usr LDFLAGS="-lm" && make && sudo make install && cd .. && rm -r ta-lib

install:
    - pip install -r requirements.txt
    - pip install codecov

script: make test

after_success:
    - codecov --token 2ae3f29d-c055-4e83-a1a9-b32526489d64

branches:
  only:
  - master

notifications:
  email: false
