trigger:
- master

jobs:
- job: 'Mac'
  pool:
    vmImage: 'macos-10.14'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar xfzv ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make -j2
        make install
      displayName: "Install system dependencies"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        python -m pip install -U --target=`pwd` --no-deps pyEX  # install latest pyEX base
        git checkout pyEX/studies # the above install clobbers source, so restore
      displayName: 'Install python dependencies'

    - script: |
        make lint
      displayName: 'Lint'

    - script: |
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'
